name: DeployToGitHubPages
env:
  PUBLISH_DIR: /home/runner/work/HappyVacations/HappyVacations/HappyVacations/bin/Release/net7.0/publish/wwwroot

# Controls when the action will run
on:
  #push:
    #branches: [ master ]
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /HappyVacations/
      
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
          # Upload entire repository
        path: ${{ env.PUBLISH_DIR }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
